/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb0_libusb0 */

#ifndef _Included_javalibusb0_libusb0
#define _Included_javalibusb0_libusb0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javalibusb0_libusb0
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javalibusb0_libusb0_init
  (JNIEnv *, jclass);

/*
 * Class:     javalibusb0_libusb0
 * Method:    jusb_find_busses
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javalibusb0_libusb0_jusb_1find_1busses
  (JNIEnv *, jclass);

/*
 * Class:     javalibusb0_libusb0
 * Method:    jusb_find_devices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javalibusb0_libusb0_jusb_1find_1devices
  (JNIEnv *, jclass);

/*
 * Class:     javalibusb0_libusb0
 * Method:    jusb_get_busses
 * Signature: ()[Ljavalibusb0/Libusb0Bus;
 */
JNIEXPORT jobjectArray JNICALL Java_javalibusb0_libusb0_jusb_1get_1busses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
