JAVA_HOME  ?= /System/Library/Frameworks/JavaVM.framework/Home
PKG_CONFIG ?= /opt/local/bin/pkg-config
CCFLAGS    := $(shell $(PKG_CONFIG) --cflags libusb-legacy)
LDFLAGS    := $(shell $(PKG_CONFIG) --libs libusb-legacy)

LIBTOOL     = /opt/local/bin/glibtool
SHREXT      = jnilib
