/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb1_Libusb1UsbDevice */

#ifndef _Included_javalibusb1_Libusb1UsbDevice
#define _Included_javalibusb1_Libusb1UsbDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javalibusb1_Libusb1UsbDevice
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javalibusb1_Libusb1UsbDevice_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javalibusb1_Libusb1UsbDevice
 * Method:    nativeGetString
 * Signature: (JBI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javalibusb1_Libusb1UsbDevice_nativeGetString
  (JNIEnv *, jobject, jlong, jbyte, jint);

#ifdef __cplusplus
}
#endif
#endif
