/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb1_impl_Libusb1UsbDevice */

#ifndef _Included_javalibusb1_impl_Libusb1UsbDevice
#define _Included_javalibusb1_impl_Libusb1UsbDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javalibusb1_impl_Libusb1UsbDevice
 * Method:    closeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javalibusb1_impl_Libusb1UsbDevice_closeNative
  (JNIEnv *, jobject);

/*
 * Class:     javalibusb1_impl_Libusb1UsbDevice
 * Method:    getStringNative
 * Signature: (BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javalibusb1_impl_Libusb1UsbDevice_getStringNative
  (JNIEnv *, jobject, jbyte, jint);

/*
 * Class:     javalibusb1_impl_Libusb1UsbDevice
 * Method:    nativeGetActiveUsbConfiguration
 * Signature: ()Ljavax/usb/UsbConfiguration;
 */
JNIEXPORT jobject JNICALL Java_javalibusb1_impl_Libusb1UsbDevice_nativeGetActiveUsbConfiguration
  (JNIEnv *, jobject);

/*
 * Class:     javalibusb1_impl_Libusb1UsbDevice
 * Method:    nativeGetUsbConfiguration
 * Signature: (B)Ljavax/usb/UsbConfiguration;
 */
JNIEXPORT jobject JNICALL Java_javalibusb1_impl_Libusb1UsbDevice_nativeGetUsbConfiguration
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
