/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb1_impl_Libusb1UsbPipe */

#ifndef _Included_javalibusb1_impl_Libusb1UsbPipe
#define _Included_javalibusb1_impl_Libusb1UsbPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javalibusb1_impl_Libusb1UsbPipe
 * Method:    nativeSyncSubmit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javalibusb1_impl_Libusb1UsbPipe_nativeSyncSubmit
  (JNIEnv *, jobject);

/*
 * Class:     javalibusb1_impl_Libusb1UsbPipe
 * Method:    nativeSyncSubmitControl
 * Signature: (IBBSSJ)I
 */
JNIEXPORT jint JNICALL Java_javalibusb1_impl_Libusb1UsbPipe_nativeSyncSubmitControl
  (JNIEnv *, jobject, jint, jbyte, jbyte, jshort, jshort, jlong);

#ifdef __cplusplus
}
#endif
#endif
