/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb1_libusb1 */

#ifndef _Included_javalibusb1_libusb1
#define _Included_javalibusb1_libusb1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javalibusb1_libusb1
 * Method:    set_trace_calls
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javalibusb1_libusb1_set_1trace_1calls
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     javalibusb1_libusb1
 * Method:    create
 * Signature: ()Ljavalibusb1/libusb1;
 */
JNIEXPORT jobject JNICALL Java_javalibusb1_libusb1_create
  (JNIEnv *, jclass);

/*
 * Class:     javalibusb1_libusb1
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javalibusb1_libusb1_close
  (JNIEnv *, jobject);

/*
 * Class:     javalibusb1_libusb1
 * Method:    set_debug
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javalibusb1_libusb1_set_1debug
  (JNIEnv *, jobject, jint);

/*
 * Class:     javalibusb1_libusb1
 * Method:    get_devices
 * Signature: ()[Ljavalibusb1/impl/Libusb1UsbDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_javalibusb1_libusb1_get_1devices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
