/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javalibusb1_Libusb1UsbPipe */

#ifndef _Included_javalibusb1_Libusb1UsbPipe
#define _Included_javalibusb1_Libusb1UsbPipe
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
