JAVA_HOME  ?= /System/Library/Frameworks/JavaVM.framework/Home
PKG_CONFIG ?= /opt/local/bin/pkg-config
CCFLAGS    ?= $(shell $(PKG_CONFIG) --cflags libusb-1.0)
LDFLAGS    ?= $(shell $(PKG_CONFIG) --libs libusb-1.0)

LIBTOOL     = /opt/local/bin/glibtool
SHREXT      = jnilib
